[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.2"
  export = ["dddss"]
  name = "dddss"
  version="1.0.0"
  org = "ramithjayasingheznszn"

[[platform.java11.dependency]]
artifactId = "h2"
version = "2.1.210"
groupId = "com.h2database"
[[platform.java11.dependency]]
path="lib/flags-1.0.jar"